name:                lambda-heights-client-generic
version:             1.2.0
github:              "morgenthum/lambda-heights"
license:             BSD3
author:              "Mario Morgenthum"
maintainer:          "mario.morgenthum@gmail.com"
copyright:           "2019 Mario Morgenthum"

description:         Please see the README on GitHub at <https://github.com/morgenthum/lambda-heights#readme>

dependencies:
  - base >=4.7 && <5
  - file-embed >= 0.0.11
  - lambda-heights-client
  - sdl2 >= 2.4.1.0
  - sdl2-ttf >= 2.1.0

executable:
  main:                Main.hs
  source-dirs:         src
  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -Wall
  - -O2
