name:                lambda-heights
version:             0.1.0.0
github:              "morgenthum/lambda-heights"
license:             BSD3
author:              "Mario Morgenthum"
maintainer:          "mario.morgenthum@gmail.com"
copyright:           "2019 Mario Morgenthum"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/morgenthum/lambda-heights#readme>

dependencies:
- async >= 2.2.1
- base >=4.7 && <5
- bytestring >= 0.10.8.2
- containers >= 0.6.0.1
- directory >= 1.3.3.0
- extra >= 1.6.14
- linear >= 1.20.8
- matrix >= 0.3.6.1
- mtl >= 2.2.2
- serialise >= 0.2.1.0
- sdl2 >= 2.4.1.0
- sdl2-gfx >= 0.2
- sdl2-ttf >= 2.1.0
- split >= 0.2.3.3
- stm >= 2.5.0.0
- text >= 1.2.3.1
- time >= 1.8.0.2
- vector >= 0.12.0.2
- yaml >= 0.11.0.0

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -O2

executables:
  lambda-heights-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O2
    dependencies:
    - lambda-heights

tests:
  lambda-heights-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-heights
