resolver: lts-13.23

packages:
- lambda-heights
- lambda-heights-app
- lambda-heights-app-win

extra-deps:
- git: https://github.com/morgenthum/compose-engine
  commit: 24e0dd5cdd5b3ae87a302466fcb1483f3875206a