name:                lambda-heights-core
version:             1.2.0
github:              "morgenthum/lambda-heights"
license:             BSD3
author:              "Mario Morgenthum"
maintainer:          "mario.morgenthum@gmail.com"
copyright:           "2019 Mario Morgenthum"

description:         Please see the README on GitHub at <https://github.com/morgenthum/lambda-heights#readme>

dependencies:
- base >=4.7 && <5
- linear >= 1.20.8
- mtl >= 2.2.2
- serialise >= 0.2.1.0
- sdl2 >= 2.4.1.0

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fno-warn-name-shadowing
  - -O2
